accton-csp7551-sfp: fix build error
Building accton-csp7551-sfp fails because the build process cannot find
symbols defined by accton-csp7551-cpld (external modules cannot see
symbols defined by other external modules). Set KBUILD_MODPOST_WARN=1
to avoid this error.

Fixes this build error:

DEBUG: Executing shell function do_compile
NOTE: make -j 16 KERNEL_SRC=/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source KERNEL_PATH=/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source KERNEL_VERSION=5.15.44-yocto-standard-onl CC=ccache x86_64-poky-linux-gcc  -fuse-ld=bfd -fmacro-prefix-map=/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0=/usr/src/debug/accton-csp7551-sfp-mod/1.0-r0                      -fdebug-prefix-map=/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0=/usr/src/debug/accton-csp7551-sfp-mod/1.0-r0                      -fdebug-prefix-map=/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/recipe-sysroot-native=  -fdebug-prefix-map=/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source=/usr/src/kernel LD=ccache x86_64-poky-linux-ld.bfd  AR=ccache x86_64-poky-linux-ar  O=/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
make -C /tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source M=/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0
make[1]: Entering directory '/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source'
make[2]: Entering directory '/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-build-artifacts'
  CC [M]  /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/x86-64-accton-csp7551-sfp.o
  MODPOST /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/Module.symvers
ERROR: modpost: "accton_i2c_cpld_read" [/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/x86-64-accton-csp7551-sfp.ko] undefined!
ERROR: modpost: "accton_i2c_cpld_write" [/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/x86-64-accton-csp7551-sfp.ko] undefined!
make[3]: *** [/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source/scripts/Makefile.modpost:134: /tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/Module.symvers] Error 1
make[3]: *** Deleting file '/tmp/accton-csp7551/work/accton_csp7551-poky-linux/accton-csp7551-sfp-mod/1.0-r0/Module.symvers'
make[2]: Leaving directory '/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-build-artifacts'
make[2]: *** [/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source/Makefile:1783: modules] Error 2
make[1]: Leaving directory '/tmp/accton-csp7551/work-shared/accton-csp7551/kernel-source'
make[1]: *** [Makefile:219: __sub-make] Error 2
make: *** [Makefile:6: all] Error 2
ERROR: oe_runmake failed
WARNING: exit code 1 from a shell command.

Signed-off-by: Roger Luethi <roger.luethi@bisdn.de>